#!/usr/bin/env bash
# Detects conflicts between documents: duplicate authority topics, deprecated
# docs still referenced as authority, and orphaned file references.
# Usage: ./scripts/check-conflicts.sh
# Output: docs/CONFLICTS.md (auto-generated conflict report)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCS_DIR="$PROJECT_ROOT/docs"
AUTHORITY="$DOCS_DIR/AUTHORITY.md"
DECISIONS_DIR="$DOCS_DIR/decisions"
CONFLICTS_OUT="$DOCS_DIR/CONFLICTS.md"

CRITICAL=0
WARNING=0
INFO=0
ISSUES=""

add_issue() {
  local sev="$1" msg="$2" fix="$3"
  ISSUES="${ISSUES}| ${sev} | ${msg} | ${fix} |
"
  case "$sev" in
    critical) CRITICAL=$((CRITICAL + 1)) ;;
    warning)  WARNING=$((WARNING + 1)) ;;
    info)     INFO=$((INFO + 1)) ;;
  esac
}

extract_path() {
  echo "$1" | sed 's/.*`\.\//\.\//' | sed 's/`.*//'
}

echo "=== Conflict Detection ==="
echo ""

# --- Check 1: Duplicate authority topics ---
echo "[1/4] Checking for duplicate authority topics..."

if [[ ! -f "$AUTHORITY" ]]; then
  add_issue "critical" "AUTHORITY.md not found" "Create docs/AUTHORITY.md"
else
  declare -A TOPIC_COUNT 2>/dev/null || true
  while IFS='|' read -r _ topic doc _; do
    topic="$(echo "$topic" | xargs 2>/dev/null || echo "")"
    [[ -z "$topic" || "$topic" == "Topic / Domain" || "$topic" == "---" ]] && continue
    [[ "$topic" == *"---"* ]] && continue
    count=$(grep -c "| ${topic} |" "$AUTHORITY" 2>/dev/null || echo "0")
    if [[ "$count" -gt 1 ]]; then
      add_issue "critical" \
        "Duplicate authority topic: '${topic}' appears ${count} times" \
        "Remove duplicate rows — each topic must have exactly one entry"
    fi
  done < "$AUTHORITY"
fi
echo ""

# --- Check 2: Deprecated documents referenced as authority ---
echo "[2/4] Checking for deprecated docs referenced as authority..."

if [[ -f "$AUTHORITY" && -d "$DECISIONS_DIR" ]]; then
  while IFS='|' read -r _ topic doc _; do
    doc="$(echo "$doc" | xargs 2>/dev/null || echo "")"
    [[ -z "$doc" || "$doc" == "Authoritative Document" ]] && continue
    [[ "$doc" == *"---"* ]] && continue

    filepath="$(extract_path "$doc")"
    [[ -z "$filepath" || "$filepath" == "$doc" ]] && continue

    resolved="$DOCS_DIR/$filepath"

    if [[ "$filepath" == *"decisions/ADR-"* && -f "$resolved" ]]; then
      status=$(grep -A2 "^## Status" "$resolved" 2>/dev/null | tail -1 | xargs 2>/dev/null || echo "")
      if [[ "$status" == "deprecated" ]]; then
        topic_name="$(echo "$topic" | xargs 2>/dev/null || echo "unknown")"
        add_issue "critical" \
          "Deprecated ADR still authoritative: ${filepath} (topic: ${topic_name})" \
          "Update AUTHORITY.md to point to the replacement ADR"
      fi
    fi
  done < "$AUTHORITY"
fi
echo ""

# --- Check 3: Orphaned references (files that don't exist) ---
echo "[3/4] Checking for orphaned file references in AUTHORITY.md..."

if [[ -f "$AUTHORITY" ]]; then
  while IFS='|' read -r _ topic doc _; do
    doc="$(echo "$doc" | xargs 2>/dev/null || echo "")"
    [[ -z "$doc" || "$doc" == "Authoritative Document" ]] && continue
    [[ "$doc" == *"---"* ]] && continue

    filepath="$(extract_path "$doc")"
    [[ -z "$filepath" || "$filepath" == "$doc" ]] && continue

    resolved="$DOCS_DIR/$filepath"
    if [[ ! -e "$resolved" ]]; then
      add_issue "critical" \
        "Orphaned reference: ${filepath} does not exist" \
        "Update or remove the broken reference in AUTHORITY.md"
    fi
  done < "$AUTHORITY"
fi
echo ""

# --- Check 4: Deprecated ADRs without forward pointers ---
echo "[4/4] Checking deprecated ADRs for forward pointers..."

ACTIVE_ADRS=0
DEPRECATED_ADRS=0

if [[ -d "$DECISIONS_DIR" ]]; then
  for adr in "$DECISIONS_DIR"/ADR-*.md; do
    [[ -f "$adr" ]] || continue

    status=$(grep -A2 "^## Status" "$adr" 2>/dev/null | tail -1 | xargs 2>/dev/null || echo "")
    adr_name="$(basename "$adr")"

    if [[ "$status" == "deprecated" ]]; then
      DEPRECATED_ADRS=$((DEPRECATED_ADRS + 1))
      superseded=$(grep -A2 "^## Superseded By" "$adr" 2>/dev/null | tail -1 | xargs 2>/dev/null || echo "")
      if [[ -z "$superseded" || "$superseded" == "active" || "$superseded" == "none" ]]; then
        add_issue "warning" \
          "Deprecated ${adr_name} has no forward pointer (Superseded By)" \
          "Add Superseded By field or use scripts/supersede-decision.sh"
      fi
    else
      ACTIVE_ADRS=$((ACTIVE_ADRS + 1))
    fi
  done
  echo "  Active ADRs: $ACTIVE_ADRS | Deprecated: $DEPRECATED_ADRS"
fi
echo ""

# --- Generate CONFLICTS.md ---
cat > "$CONFLICTS_OUT" << EOF
# Conflict Report — Auto-Generated

> Generated by \`scripts/check-conflicts.sh\`. Do not edit manually.

## Summary

- **Critical:** $CRITICAL
- **Warning:** $WARNING
- **Info:** $INFO

## Issues

| Severity | Issue | Suggested Resolution |
|---|---|---|
${ISSUES}
## How to Resolve

1. **Critical** — Must fix before starting new work
2. **Warning** — Fix soon; does not block work
3. **Info** — Suggestions for improvement

Run \`scripts/check-conflicts.sh\` again after fixing to verify resolution.
EOF

echo "=== Conflict Report ==="
echo "  Critical: $CRITICAL"
echo "  Warning:  $WARNING"
echo "  Info:     $INFO"
echo "  Report:   docs/CONFLICTS.md"

if [[ "$CRITICAL" -gt 0 ]]; then
  echo ""
  echo "CRITICAL CONFLICTS — resolve before proceeding."
  exit 1
fi

echo ""
echo "No critical conflicts found."
exit 0
