#!/usr/bin/env bash
# Scans docs/decisions/, docs/journals/, docs/deliberations/ and regenerates
# docs/TIMELINE.md with all entries in reverse chronological order.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TIMELINE="$REPO_ROOT/docs/TIMELINE.md"

entries=()

for file in "$REPO_ROOT"/docs/decisions/ADR-*.md; do
  [ -f "$file" ] || continue
  id=$(basename "$file" .md)
  title=$(head -1 "$file" | sed 's/^# *//; s/^ADR-[0-9]*: *//')
  date=$(grep -A2 '^## Date' "$file" | tail -1 | tr -d '[:space:]')
  [ -z "$date" ] && date="unknown"
  entries+=("${date}|ADR|${id}|${title}|./decisions/${id}.md")
done

for file in "$REPO_ROOT"/docs/journals/JOURNAL-*.md; do
  [ -f "$file" ] || continue
  id=$(basename "$file" .md)
  title=$(head -1 "$file" | sed 's/^# *//; s/^JOURNAL-[0-9]*: *//')
  date=$(grep -A2 '^## Date' "$file" | tail -1 | tr -d '[:space:]')
  [ -z "$date" ] && date="unknown"
  entries+=("${date}|JOURNAL|${id}|${title}|./journals/${id}.md")
done

for file in "$REPO_ROOT"/docs/deliberations/DELIB-*.md; do
  [ -f "$file" ] || continue
  id=$(basename "$file" .md)
  title=$(head -1 "$file" | sed 's/^# *//; s/^DELIB-[0-9]*: *//')
  date=$(grep -A2 '^## Date' "$file" | tail -1 | tr -d '[:space:]')
  [ -z "$date" ] && date="unknown"
  entries+=("${date}|DELIB|${id}|${title}|./deliberations/${id}.md")
done

cat > "$TIMELINE" << 'HEADER'
# Project Timeline

All decisions, journals, and deliberation logs in reverse chronological order.
Auto-generated by `scripts/update-timeline.sh` — do not edit manually.

| Date | Type | ID | Title | Link |
|------|------|----|-------|------|
HEADER

if [ ${#entries[@]} -eq 0 ]; then
  echo "| — | — | — | No entries yet | — |" >> "$TIMELINE"
else
  IFS=$'\n' sorted=($(printf '%s\n' "${entries[@]}" | sort -r -t'|' -k1,1))
  unset IFS
  for entry in "${sorted[@]}"; do
    date=$(echo "$entry" | cut -d'|' -f1)
    type=$(echo "$entry" | cut -d'|' -f2)
    id=$(echo "$entry" | cut -d'|' -f3)
    title=$(echo "$entry" | cut -d'|' -f4)
    link=$(echo "$entry" | cut -d'|' -f5)
    echo "| ${date} | ${type} | ${id} | ${title} | [${id}](${link}) |" >> "$TIMELINE"
  done
fi

count=${#entries[@]}
echo ""
echo "✓ TIMELINE.md updated with ${count} entries"
